### ISSUE TITLE
Research & Design Optical Tracking

### ISSUE THREAD

**Issue by fbl100** [fbl100/FLL-2018#2]
Research how we might track astronaut movements and convert them into gestures

**Comment by zarna-caer** [comment]
From my research, I found there are two forms of motion tracking for vr, outside in and inside out. For outside in, there are cameras set up throughout the room tracking dots on the person and headset. It is more accurate, but gives limited room, which is not a problem for our uses. For inside out, it puts a gyroscope inside the headset itself to see where you are looking which is less accurate, however it provides more freedom to move about, which is not necessary given our application of the technology. Overall I feel the outside-in would be our best choice for we need higher precision and area of effect is not really an issue. As for the hand symbols I found this website: http://www.roborealm.com/tutorial/Hand_Gestures/index.php 
that shows how to identify hand symbols of your choice. However that method becomes shaky when you are not just simply putting certain fingers out. While it is still functioning, it is not as accurate as you can see when they try to use what I can only describe as an "o" with their hand for a 10 (You will understand my statement if you scroll down and watch the video of the method's practical application). I feel we could set up cameras about the control room and one or two above where the controllers hands are for maximum accuracy. This is necessary for the emergency repairs that we would be partaking in since accuracy is generally considered a good thing in that kind of situation. That is all for now.
